services:
  backend:
    build: ./backend
    expose:
      - "9292"
    environment:
      - SESSION_SECRET
      - OIDC_ISSUER
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - OIDC_REDIRECT_URI
      - FRONTEND_URL=https://kks08kkcg88ckkcocwooc4ck.a.selfhosted.hackclub.com
      - AIRTABLE_BASE_ID
      - AIRTABLE_PAT

  frontend:
    build: .
    expose:
      - "3000"
    environment:
      - ORIGIN=https://kks08kkcg88ckkcocwooc4ck.a.selfhosted.hackclub.com
      - BACKEND_URL=http://backend:9292
    depends_on:
      - backend
